# Generated by Django 2.1 on 2018-09-10 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('image_url', models.ImageField(upload_to='ad/%Y/%m', verbose_name='图片路径')),
                ('date_publish', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('index', models.IntegerField(default=1, verbose_name='排列顺序')),
            ],
            options={
                'verbose_name': '广告',
                'verbose_name_plural': '广告',
                'ordering': ['index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='品牌名称')),
                ('index', models.IntegerField(default=1, verbose_name='排列顺序')),
            ],
            options={
                'verbose_name': '品牌',
                'verbose_name_plural': '品牌',
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='Caritem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='数量')),
                ('sum_price', models.FloatField(default=0.0, verbose_name='小计')),
            ],
            options={
                'verbose_name': '购物车条目',
                'verbose_name_plural': '购物车条目',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(max_length=20, verbose_name='所属大类')),
                ('name', models.CharField(max_length=30, verbose_name='分类名称')),
                ('index', models.IntegerField(default=1, verbose_name='分类的排序')),
                ('sex', models.IntegerField(default=0, verbose_name='性别')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'ordering': ['index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名称')),
                ('old_price', models.FloatField(default=0.0, verbose_name='原价')),
                ('new_price', models.FloatField(default=0.0, verbose_name='现价')),
                ('discount', models.FloatField(default=1, verbose_name='折扣')),
                ('desc', models.CharField(max_length=100, verbose_name='简介')),
                ('sales', models.IntegerField(default=0, verbose_name='销量')),
                ('num', models.IntegerField(default=0, verbose_name='库存')),
                ('image_url_i', models.ImageField(default='clothing/default.jpg', upload_to='clothing/%Y/%m', verbose_name='展示图片路径')),
                ('image_url_l', models.ImageField(default='clothing/default.jpg', upload_to='clothing/%Y/%m', verbose_name='详情图片路径1')),
                ('image_url_m', models.ImageField(default='clothing/default.jpg', upload_to='clothing/%Y/%m', verbose_name='详情图片路径2')),
                ('image_url_r', models.ImageField(default='clothing/default.jpg', upload_to='clothing/%Y/%m', verbose_name='详情图片路径3')),
                ('image_url_c', models.ImageField(default='clothing/ce.jpg', upload_to='clothing/%Y/%m', verbose_name='购物车展示图片')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Brand', verbose_name='品牌')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Category', verbose_name='分类')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='尺寸')),
                ('index', models.IntegerField(default=1, verbose_name='排列顺序')),
            ],
            options={
                'verbose_name': '尺寸',
                'verbose_name_plural': '尺寸',
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='标签')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.AddField(
            model_name='clothing',
            name='size',
            field=models.ManyToManyField(to='store.Size', verbose_name='尺寸'),
        ),
        migrations.AddField(
            model_name='clothing',
            name='tag',
            field=models.ManyToManyField(to='store.Tag', verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='caritem',
            name='clothing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Clothing', verbose_name='购物车中产品条目'),
        ),
    ]
