# Generated by Django 2.1 on 2018-09-11 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fingerprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_hash', models.BinaryField(max_length=10, verbose_name='歌曲hash')),
                ('offset', models.IntegerField(verbose_name='片段所在歌曲中的偏移')),
            ],
            options={
                'verbose_name': '歌曲片段指纹',
                'verbose_name_plural': '歌曲片段指纹',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='歌曲名字')),
                ('file_sha1', models.BinaryField(max_length=20, verbose_name='文件sha1')),
                ('fingerprinted', models.BooleanField(verbose_name='是否已被记录')),
            ],
            options={
                'verbose_name': '歌曲详情',
                'verbose_name_plural': '歌曲详情',
            },
        ),
        migrations.AddField(
            model_name='fingerprint',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dejavu.Song', verbose_name='对应的歌曲'),
        ),
    ]
