# Generated by Django 2.1 on 2018-09-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dejavu', '0002_auto_20180912_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(max_length=80, verbose_name='歌曲名字'),
        ),
    ]
